---
title: "Demo Stylish Article"
# Output formats
format:
  stylisharticle-pdf:
    keep-tex: true
    # Color example, see "Text color"
    header-includes:
      \definecolor{grey}{RGB}{191, 191, 191}
  stylisharticle-html:
    # Color example, see "Text color"
    css: colors.css
# Authors (https://quarto.org/docs/journals/authors.html#author-schema)
author:
  - name: Félix Romiguière
    affiliations:
      - name: Université de Montpellier
        department: Scientific Department
        address: Somewhere
        city: City
        country: Country
        postal-code: 9999
    orcid: 0000-0000-0000-0000
    email: JD@example.org
    url: https://example.org/
# Abstract and Keywords
abstract: |
  This document is only a demo explaining how to use the Stylish Article template.
keywords: [template, demo]
# Bibliography
reference-section-title: References
bibliography: references.bib
# Language
lang: fr-FR
otherlangs: en-GB
# Code options 
# https://quarto.org/docs/computations/execution-options.html
execute:
  # show code chunk output
  include: true
  # Show the code in the output
  echo: false
  # Show messages
  message: false
  # Show warnings
  warning: false
  # Cache code results
  cache: true
# Template specific
journalinfo: "Publication reference"
archive: "DOI: xxx/xx"
keywordlabel: Keywords
corrauthorlabel: Corresponding Author
---

```{r}
#| label: Options
### Customized R options for this document
# Delete this chunk if you don't use R

# Necessary packages. Add all packages used in the code here.
packages_required <- c(
  # R tools, do not modify
  "knitr",
  # Add specific packages here
  "divent",
  "tidyverse", 
  "vegan"
)
# Already installed?
packages_installed <- vapply(
  packages_required, 
  FUN = requireNamespace, 
  FUN.VALUE = TRUE, 
  quietly = TRUE
) 
# Install missing packages
install.packages(names(packages_installed)[!packages_installed])

# Allow size='small' or any valid Latex font size in chunk options
def.chunk.hook <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(
  chunk = function(x, options) {
    x <- def.chunk.hook(x, options)
    ifelse(
      options$size == "normalsize", 
      yes = x,
      no = paste0("\n \\", options$size, "\n\n", x, "\n\n \\normalsize")
    )
  }
)

# knitr options (https://yihui.org/knitr/options/)
knitr::opts_chunk$set(
  # Code chunk automatic format if tidy is TRUE
  tidy = TRUE, 
  # Tidy code options: remove blank lines and cut lines after 50 characters
  tidy.opts = list(blank = FALSE, width.cutoff = 50),
  # Font size in PDF output
  size = "scriptsize", 
  # Select PDF figures in PDF output if PDF file exists beside PNG file
  knitr.graphics.auto_pdf = TRUE
)
# Text width of R functions output
options(width = 50)

# ggplot style
library("tidyverse")
# Function to call in each chunk that produces a figure
ggtheme_set <- function() {
  theme_set(theme_bw())
  theme_update(
    panel.background = element_rect(fill = "transparent", colour = NA),
    plot.background = element_rect(fill = "transparent", colour = NA)
  )
}
knitr::opts_chunk$set(dev.args = list(bg = "transparent"))

# Random seed
set.seed(973)
```

# Introduction

# Matériels et Méthodes

- Site de Paracou Comparer la diversité de Paracou [@Gourlet-Fleury2004] et de BCI [@Raby2017].
- Site de BCI

```{r}
#| label: Paracou_BCI
library("tidyverse")
paracou6 <- read_csv2("data/Paracou6.csv")
library("vegan")
data(BCI)
library("divent")
BCI %>% 
  # Création d'un objet "abundances"
  as_abundances() %>% 
  # Les poids des parcelles sont égaux
  mutate(weight = 1) %>% 
  # Regrouper toutes les parcelles
  metacommunity() ->
  BCI_50ha
```

# Résultats

::: {#fig-compa}
```{r}
#| label: compa
#| out-width: 50%
paracou6 %>% 
  # Vecteur des noms d'espèce de chaque arbre
  pull(spName) %>% 
  # Création d'un objet "abundances"
  as_abundances() %>% 
  # Ajout des données de BCI
  bind_rows(BCI_50ha) %>% 
  # Remplacement des NA par 0
  mutate(across(everything(), ~ replace_na(.x, 0))) %>% 
  # Nom des sites
  mutate(site = c("Paracou", "BCI")) %>% 
  # Profil de diversité avec enveloppe de confiance
  profile_hill(n_simulations = 2) %>% 
  # Figure
  autoplot() +
  # Titre de la légende
  labs(color = "Forêt", linetype = "Forêt")
```

Différence de valeurs de diversité en fonction de son ordre entre les sites de Paracou et BCI
:::

# Discussion

Bonus sur la thématique Tahiti_Soundscape

```{r}
#| label: Tahiti
library(readxl)
Data_Globale_Tahiti <- read_excel("data/Excel_DataBrut/Data_Globale_Tahiti.xlsx")
```


::: {#fig-gradient}

```{r}
#| label: gradient
# On crée un index numérique pour l’axe x
Data_Globale_Tahiti <- Data_Globale_Tahiti %>%
  mutate(x_id = as.numeric(factor(Enr)))

# Dataset pour les rectangles de fond
communes_bg <- Data_Globale_Tahiti %>%
  group_by(Commune) %>%
  summarise(
    xmin = min(x_id) - 0.5,
    xmax = max(x_id) + 0.5
  )
# Coefficient pour mettre l'altitude à l'échelle des HSA
coef_alt <- max(Data_Globale_Tahiti$`HSA`, na.rm = TRUE) /
            max(Data_Globale_Tahiti$`Alt`, na.rm = TRUE)

ggplot() +
  # Fond coloré discret
  geom_rect(data = communes_bg,
            aes(xmin = xmin, xmax = xmax,
                ymin = -Inf, ymax = Inf,
                fill = Commune),
            alpha = 0.08) +
  
  # Barres HSA
  geom_col(data = Data_Globale_Tahiti,
           aes(x = x_id, y = `HSA`),
           fill = "grey40") +
  
  # Points altitude (mis à l’échelle)
  geom_point(data = Data_Globale_Tahiti,
             aes(x = x_id, y = `Alt` * coef_alt),
             shape = 4,              # croix
             color = "#E5989B",      # rouge pastel doux
             size = 2,
             stroke = 0.8,
             alpha = 0.8) +
  
  scale_x_continuous(
    breaks = Data_Globale_Tahiti$x_id,
    labels = Data_Globale_Tahiti$Enr
  ) +
  geom_line(data = Data_Globale_Tahiti,
          aes(x = x_id, y = `Alt`* coef_alt, group = 1),
          color = "#E5989B",
          linewidth = 0.7) +
  
  scale_y_continuous(
    name = "Hard Surface Area (%)",
    sec.axis = sec_axis(~ . / coef_alt,
                        name = "Altitude (m)")
  ) +
  
  scale_fill_brewer(palette = "Paired") +
  
  labs(x = "Site",
       caption = "Gradient site") +
  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
Gradient d'HardSurfaceArea (%) et d'Altitude (m) en fonction des sites étudiés
:::
